#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMEXCHANGE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NACOSA")]
	public partial class NacosadbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAssessment(Assessment instance);
    partial void UpdateAssessment(Assessment instance);
    partial void DeleteAssessment(Assessment instance);
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void InsertJourney(Journey instance);
    partial void UpdateJourney(Journey instance);
    partial void DeleteJourney(Journey instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUserRegistration(UserRegistration instance);
    partial void UpdateUserRegistration(UserRegistration instance);
    partial void DeleteUserRegistration(UserRegistration instance);
    #endregion
		
		public NacosadbDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["surveyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NacosadbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NacosadbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NacosadbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NacosadbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Province> Provinces
		{
			get
			{
				return this.GetTable<Province>();
			}
		}
		
		public System.Data.Linq.Table<Region> Regions
		{
			get
			{
				return this.GetTable<Region>();
			}
		}
		
		public System.Data.Linq.Table<Assessment> Assessments
		{
			get
			{
				return this.GetTable<Assessment>();
			}
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<Journey> Journeys
		{
			get
			{
				return this.GetTable<Journey>();
			}
		}
		
		public System.Data.Linq.Table<Region1> Region1s
		{
			get
			{
				return this.GetTable<Region1>();
			}
		}
		
		public System.Data.Linq.Table<Role> Roles
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<vw_DisplayAGYWInfo> vw_DisplayAGYWInfos
		{
			get
			{
				return this.GetTable<vw_DisplayAGYWInfo>();
			}
		}
		
		public System.Data.Linq.Table<UserRegistration> UserRegistrations
		{
			get
			{
				return this.GetTable<UserRegistration>();
			}
		}
		
		public System.Data.Linq.Table<QualityAssured> QualityAssureds
		{
			get
			{
				return this.GetTable<QualityAssured>();
			}
		}
		
		public System.Data.Linq.Table<NotQualityAssured> NotQualityAssureds
		{
			get
			{
				return this.GetTable<NotQualityAssured>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Province")]
	public partial class Province
	{
		
		private int _ProvinceID;
		
		private string _ProvinceName;
		
		public Province()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ProvinceID
		{
			get
			{
				return this._ProvinceID;
			}
			set
			{
				if ((this._ProvinceID != value))
				{
					this._ProvinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceName", DbType="NVarChar(50)")]
		public string ProvinceName
		{
			get
			{
				return this._ProvinceName;
			}
			set
			{
				if ((this._ProvinceName != value))
				{
					this._ProvinceName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Regions")]
	public partial class Region
	{
		
		private int _RegionID;
		
		private int _ProvinceID;
		
		private string _RegionName;
		
		public Region()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceID", DbType="Int NOT NULL")]
		public int ProvinceID
		{
			get
			{
				return this._ProvinceID;
			}
			set
			{
				if ((this._ProvinceID != value))
				{
					this._ProvinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionName", DbType="NVarChar(50)")]
		public string RegionName
		{
			get
			{
				return this._RegionName;
			}
			set
			{
				if ((this._RegionName != value))
				{
					this._RegionName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Assessment")]
	public partial class Assessment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _LiveWithParents;
		
		private string _Schooling;
		
		private string _CompletedSchool;
		
		private string _HighestGrade;
		
		private string _Children;
		
		private System.Nullable<int> _HowManyChildren;
		
		private string _MaritalStatus;
		
		private System.Nullable<int> _regID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLiveWithParentsChanging(string value);
    partial void OnLiveWithParentsChanged();
    partial void OnSchoolingChanging(string value);
    partial void OnSchoolingChanged();
    partial void OnCompletedSchoolChanging(string value);
    partial void OnCompletedSchoolChanged();
    partial void OnHighestGradeChanging(string value);
    partial void OnHighestGradeChanged();
    partial void OnChildrenChanging(string value);
    partial void OnChildrenChanged();
    partial void OnHowManyChildrenChanging(System.Nullable<int> value);
    partial void OnHowManyChildrenChanged();
    partial void OnMaritalStatusChanging(string value);
    partial void OnMaritalStatusChanged();
    partial void OnregIDChanging(System.Nullable<int> value);
    partial void OnregIDChanged();
    #endregion
		
		public Assessment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiveWithParents", DbType="VarChar(255)")]
		public string LiveWithParents
		{
			get
			{
				return this._LiveWithParents;
			}
			set
			{
				if ((this._LiveWithParents != value))
				{
					this.OnLiveWithParentsChanging(value);
					this.SendPropertyChanging();
					this._LiveWithParents = value;
					this.SendPropertyChanged("LiveWithParents");
					this.OnLiveWithParentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Schooling", DbType="VarChar(255)")]
		public string Schooling
		{
			get
			{
				return this._Schooling;
			}
			set
			{
				if ((this._Schooling != value))
				{
					this.OnSchoolingChanging(value);
					this.SendPropertyChanging();
					this._Schooling = value;
					this.SendPropertyChanged("Schooling");
					this.OnSchoolingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompletedSchool", DbType="VarChar(255)")]
		public string CompletedSchool
		{
			get
			{
				return this._CompletedSchool;
			}
			set
			{
				if ((this._CompletedSchool != value))
				{
					this.OnCompletedSchoolChanging(value);
					this.SendPropertyChanging();
					this._CompletedSchool = value;
					this.SendPropertyChanged("CompletedSchool");
					this.OnCompletedSchoolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighestGrade", DbType="VarChar(255)")]
		public string HighestGrade
		{
			get
			{
				return this._HighestGrade;
			}
			set
			{
				if ((this._HighestGrade != value))
				{
					this.OnHighestGradeChanging(value);
					this.SendPropertyChanging();
					this._HighestGrade = value;
					this.SendPropertyChanged("HighestGrade");
					this.OnHighestGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Children", DbType="VarChar(255)")]
		public string Children
		{
			get
			{
				return this._Children;
			}
			set
			{
				if ((this._Children != value))
				{
					this.OnChildrenChanging(value);
					this.SendPropertyChanging();
					this._Children = value;
					this.SendPropertyChanged("Children");
					this.OnChildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HowManyChildren", DbType="Int")]
		public System.Nullable<int> HowManyChildren
		{
			get
			{
				return this._HowManyChildren;
			}
			set
			{
				if ((this._HowManyChildren != value))
				{
					this.OnHowManyChildrenChanging(value);
					this.SendPropertyChanging();
					this._HowManyChildren = value;
					this.SendPropertyChanged("HowManyChildren");
					this.OnHowManyChildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="VarChar(255)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this.OnMaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._MaritalStatus = value;
					this.SendPropertyChanged("MaritalStatus");
					this.OnMaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regID", DbType="Int")]
		public System.Nullable<int> regID
		{
			get
			{
				return this._regID;
			}
			set
			{
				if ((this._regID != value))
				{
					this.OnregIDChanging(value);
					this.SendPropertyChanging();
					this._regID = value;
					this.SendPropertyChanged("regID");
					this.OnregIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admin_id;
		
		private string _email;
		
		private string _password;
		
		private string _name;
		
		private string _surname;
		
		private string _role;
		
		private System.Nullable<System.DateTime> _date_created;
		
		private string _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_idChanging(int value);
    partial void Onadmin_idChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void Ondate_createdChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_createdChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(60)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(60)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(60)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(60)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_created", DbType="Date")]
		public System.Nullable<System.DateTime> date_created
		{
			get
			{
				return this._date_created;
			}
			set
			{
				if ((this._date_created != value))
				{
					this.Ondate_createdChanging(value);
					this.SendPropertyChanging();
					this._date_created = value;
					this.SendPropertyChanged("date_created");
					this.Ondate_createdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(60)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Journey")]
	public partial class Journey : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _HIVTesting;
		
		private string _HIVSelfScreening;
		
		private string _CondomsSTIScreening;
		
		private string _PregnancyTesting;
		
		private string _EmergencyContraception;
		
		private string _VendingMachines;
		
		private string _PeerEducation;
		
		private string _ComprehensiveSexualityEducation;
		
		private string _IndividualAndGroupSupport;
		
		private string _PrepDemandCreation;
		
		private string _SRHKnowledge;
		
		private string _MentalHealthSupport;
		
		private string _SupportAccessSocialGrants;
		
		private string _DignityPacks;
		
		private string _AcademicSupport;
		
		private string _ReturnToSchoolSupport;
		
		private string _ECDVouchers;
		
		private string _EconomicStrengthening;
		
		private string _WholeSchoolDevelopment;
		
		private string _MenDialoguesGenderNorms;
		
		private string _YouthLeadership;
		
		private System.Nullable<int> _regID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHIVTestingChanging(string value);
    partial void OnHIVTestingChanged();
    partial void OnHIVSelfScreeningChanging(string value);
    partial void OnHIVSelfScreeningChanged();
    partial void OnCondomsSTIScreeningChanging(string value);
    partial void OnCondomsSTIScreeningChanged();
    partial void OnPregnancyTestingChanging(string value);
    partial void OnPregnancyTestingChanged();
    partial void OnEmergencyContraceptionChanging(string value);
    partial void OnEmergencyContraceptionChanged();
    partial void OnVendingMachinesChanging(string value);
    partial void OnVendingMachinesChanged();
    partial void OnPeerEducationChanging(string value);
    partial void OnPeerEducationChanged();
    partial void OnComprehensiveSexualityEducationChanging(string value);
    partial void OnComprehensiveSexualityEducationChanged();
    partial void OnIndividualAndGroupSupportChanging(string value);
    partial void OnIndividualAndGroupSupportChanged();
    partial void OnPrepDemandCreationChanging(string value);
    partial void OnPrepDemandCreationChanged();
    partial void OnSRHKnowledgeChanging(string value);
    partial void OnSRHKnowledgeChanged();
    partial void OnMentalHealthSupportChanging(string value);
    partial void OnMentalHealthSupportChanged();
    partial void OnSupportAccessSocialGrantsChanging(string value);
    partial void OnSupportAccessSocialGrantsChanged();
    partial void OnDignityPacksChanging(string value);
    partial void OnDignityPacksChanged();
    partial void OnAcademicSupportChanging(string value);
    partial void OnAcademicSupportChanged();
    partial void OnReturnToSchoolSupportChanging(string value);
    partial void OnReturnToSchoolSupportChanged();
    partial void OnECDVouchersChanging(string value);
    partial void OnECDVouchersChanged();
    partial void OnEconomicStrengtheningChanging(string value);
    partial void OnEconomicStrengtheningChanged();
    partial void OnWholeSchoolDevelopmentChanging(string value);
    partial void OnWholeSchoolDevelopmentChanged();
    partial void OnMenDialoguesGenderNormsChanging(string value);
    partial void OnMenDialoguesGenderNormsChanged();
    partial void OnYouthLeadershipChanging(string value);
    partial void OnYouthLeadershipChanged();
    partial void OnregIDChanging(System.Nullable<int> value);
    partial void OnregIDChanged();
    #endregion
		
		public Journey()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIVTesting", DbType="VarChar(255)")]
		public string HIVTesting
		{
			get
			{
				return this._HIVTesting;
			}
			set
			{
				if ((this._HIVTesting != value))
				{
					this.OnHIVTestingChanging(value);
					this.SendPropertyChanging();
					this._HIVTesting = value;
					this.SendPropertyChanged("HIVTesting");
					this.OnHIVTestingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIVSelfScreening", DbType="VarChar(255)")]
		public string HIVSelfScreening
		{
			get
			{
				return this._HIVSelfScreening;
			}
			set
			{
				if ((this._HIVSelfScreening != value))
				{
					this.OnHIVSelfScreeningChanging(value);
					this.SendPropertyChanging();
					this._HIVSelfScreening = value;
					this.SendPropertyChanged("HIVSelfScreening");
					this.OnHIVSelfScreeningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CondomsSTIScreening", DbType="VarChar(255)")]
		public string CondomsSTIScreening
		{
			get
			{
				return this._CondomsSTIScreening;
			}
			set
			{
				if ((this._CondomsSTIScreening != value))
				{
					this.OnCondomsSTIScreeningChanging(value);
					this.SendPropertyChanging();
					this._CondomsSTIScreening = value;
					this.SendPropertyChanged("CondomsSTIScreening");
					this.OnCondomsSTIScreeningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PregnancyTesting", DbType="VarChar(255)")]
		public string PregnancyTesting
		{
			get
			{
				return this._PregnancyTesting;
			}
			set
			{
				if ((this._PregnancyTesting != value))
				{
					this.OnPregnancyTestingChanging(value);
					this.SendPropertyChanging();
					this._PregnancyTesting = value;
					this.SendPropertyChanged("PregnancyTesting");
					this.OnPregnancyTestingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyContraception", DbType="VarChar(255)")]
		public string EmergencyContraception
		{
			get
			{
				return this._EmergencyContraception;
			}
			set
			{
				if ((this._EmergencyContraception != value))
				{
					this.OnEmergencyContraceptionChanging(value);
					this.SendPropertyChanging();
					this._EmergencyContraception = value;
					this.SendPropertyChanged("EmergencyContraception");
					this.OnEmergencyContraceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendingMachines", DbType="VarChar(255)")]
		public string VendingMachines
		{
			get
			{
				return this._VendingMachines;
			}
			set
			{
				if ((this._VendingMachines != value))
				{
					this.OnVendingMachinesChanging(value);
					this.SendPropertyChanging();
					this._VendingMachines = value;
					this.SendPropertyChanged("VendingMachines");
					this.OnVendingMachinesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeerEducation", DbType="VarChar(255)")]
		public string PeerEducation
		{
			get
			{
				return this._PeerEducation;
			}
			set
			{
				if ((this._PeerEducation != value))
				{
					this.OnPeerEducationChanging(value);
					this.SendPropertyChanging();
					this._PeerEducation = value;
					this.SendPropertyChanged("PeerEducation");
					this.OnPeerEducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComprehensiveSexualityEducation", DbType="VarChar(255)")]
		public string ComprehensiveSexualityEducation
		{
			get
			{
				return this._ComprehensiveSexualityEducation;
			}
			set
			{
				if ((this._ComprehensiveSexualityEducation != value))
				{
					this.OnComprehensiveSexualityEducationChanging(value);
					this.SendPropertyChanging();
					this._ComprehensiveSexualityEducation = value;
					this.SendPropertyChanged("ComprehensiveSexualityEducation");
					this.OnComprehensiveSexualityEducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndividualAndGroupSupport", DbType="VarChar(255)")]
		public string IndividualAndGroupSupport
		{
			get
			{
				return this._IndividualAndGroupSupport;
			}
			set
			{
				if ((this._IndividualAndGroupSupport != value))
				{
					this.OnIndividualAndGroupSupportChanging(value);
					this.SendPropertyChanging();
					this._IndividualAndGroupSupport = value;
					this.SendPropertyChanged("IndividualAndGroupSupport");
					this.OnIndividualAndGroupSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrepDemandCreation", DbType="VarChar(255)")]
		public string PrepDemandCreation
		{
			get
			{
				return this._PrepDemandCreation;
			}
			set
			{
				if ((this._PrepDemandCreation != value))
				{
					this.OnPrepDemandCreationChanging(value);
					this.SendPropertyChanging();
					this._PrepDemandCreation = value;
					this.SendPropertyChanged("PrepDemandCreation");
					this.OnPrepDemandCreationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SRHKnowledge", DbType="VarChar(255)")]
		public string SRHKnowledge
		{
			get
			{
				return this._SRHKnowledge;
			}
			set
			{
				if ((this._SRHKnowledge != value))
				{
					this.OnSRHKnowledgeChanging(value);
					this.SendPropertyChanging();
					this._SRHKnowledge = value;
					this.SendPropertyChanged("SRHKnowledge");
					this.OnSRHKnowledgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MentalHealthSupport", DbType="VarChar(255)")]
		public string MentalHealthSupport
		{
			get
			{
				return this._MentalHealthSupport;
			}
			set
			{
				if ((this._MentalHealthSupport != value))
				{
					this.OnMentalHealthSupportChanging(value);
					this.SendPropertyChanging();
					this._MentalHealthSupport = value;
					this.SendPropertyChanged("MentalHealthSupport");
					this.OnMentalHealthSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportAccessSocialGrants", DbType="VarChar(255)")]
		public string SupportAccessSocialGrants
		{
			get
			{
				return this._SupportAccessSocialGrants;
			}
			set
			{
				if ((this._SupportAccessSocialGrants != value))
				{
					this.OnSupportAccessSocialGrantsChanging(value);
					this.SendPropertyChanging();
					this._SupportAccessSocialGrants = value;
					this.SendPropertyChanged("SupportAccessSocialGrants");
					this.OnSupportAccessSocialGrantsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DignityPacks", DbType="VarChar(255)")]
		public string DignityPacks
		{
			get
			{
				return this._DignityPacks;
			}
			set
			{
				if ((this._DignityPacks != value))
				{
					this.OnDignityPacksChanging(value);
					this.SendPropertyChanging();
					this._DignityPacks = value;
					this.SendPropertyChanged("DignityPacks");
					this.OnDignityPacksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcademicSupport", DbType="VarChar(255)")]
		public string AcademicSupport
		{
			get
			{
				return this._AcademicSupport;
			}
			set
			{
				if ((this._AcademicSupport != value))
				{
					this.OnAcademicSupportChanging(value);
					this.SendPropertyChanging();
					this._AcademicSupport = value;
					this.SendPropertyChanged("AcademicSupport");
					this.OnAcademicSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReturnToSchoolSupport", DbType="VarChar(255)")]
		public string ReturnToSchoolSupport
		{
			get
			{
				return this._ReturnToSchoolSupport;
			}
			set
			{
				if ((this._ReturnToSchoolSupport != value))
				{
					this.OnReturnToSchoolSupportChanging(value);
					this.SendPropertyChanging();
					this._ReturnToSchoolSupport = value;
					this.SendPropertyChanged("ReturnToSchoolSupport");
					this.OnReturnToSchoolSupportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ECDVouchers", DbType="VarChar(255)")]
		public string ECDVouchers
		{
			get
			{
				return this._ECDVouchers;
			}
			set
			{
				if ((this._ECDVouchers != value))
				{
					this.OnECDVouchersChanging(value);
					this.SendPropertyChanging();
					this._ECDVouchers = value;
					this.SendPropertyChanged("ECDVouchers");
					this.OnECDVouchersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EconomicStrengthening", DbType="VarChar(255)")]
		public string EconomicStrengthening
		{
			get
			{
				return this._EconomicStrengthening;
			}
			set
			{
				if ((this._EconomicStrengthening != value))
				{
					this.OnEconomicStrengtheningChanging(value);
					this.SendPropertyChanging();
					this._EconomicStrengthening = value;
					this.SendPropertyChanged("EconomicStrengthening");
					this.OnEconomicStrengtheningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WholeSchoolDevelopment", DbType="VarChar(255)")]
		public string WholeSchoolDevelopment
		{
			get
			{
				return this._WholeSchoolDevelopment;
			}
			set
			{
				if ((this._WholeSchoolDevelopment != value))
				{
					this.OnWholeSchoolDevelopmentChanging(value);
					this.SendPropertyChanging();
					this._WholeSchoolDevelopment = value;
					this.SendPropertyChanged("WholeSchoolDevelopment");
					this.OnWholeSchoolDevelopmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenDialoguesGenderNorms", DbType="VarChar(255)")]
		public string MenDialoguesGenderNorms
		{
			get
			{
				return this._MenDialoguesGenderNorms;
			}
			set
			{
				if ((this._MenDialoguesGenderNorms != value))
				{
					this.OnMenDialoguesGenderNormsChanging(value);
					this.SendPropertyChanging();
					this._MenDialoguesGenderNorms = value;
					this.SendPropertyChanged("MenDialoguesGenderNorms");
					this.OnMenDialoguesGenderNormsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YouthLeadership", DbType="VarChar(255)")]
		public string YouthLeadership
		{
			get
			{
				return this._YouthLeadership;
			}
			set
			{
				if ((this._YouthLeadership != value))
				{
					this.OnYouthLeadershipChanging(value);
					this.SendPropertyChanging();
					this._YouthLeadership = value;
					this.SendPropertyChanged("YouthLeadership");
					this.OnYouthLeadershipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regID", DbType="Int")]
		public System.Nullable<int> regID
		{
			get
			{
				return this._regID;
			}
			set
			{
				if ((this._regID != value))
				{
					this.OnregIDChanging(value);
					this.SendPropertyChanging();
					this._regID = value;
					this.SendPropertyChanged("regID");
					this.OnregIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Regions")]
	public partial class Region1
	{
		
		private int _RegionID;
		
		private int _ProvinceID;
		
		private string _RegionName;
		
		public Region1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this._RegionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceID", DbType="Int NOT NULL")]
		public int ProvinceID
		{
			get
			{
				return this._ProvinceID;
			}
			set
			{
				if ((this._ProvinceID != value))
				{
					this._ProvinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionName", DbType="NVarChar(50)")]
		public string RegionName
		{
			get
			{
				return this._RegionName;
			}
			set
			{
				if ((this._RegionName != value))
				{
					this._RegionName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Role
	{
		
		private int _id;
		
		private string _roleTitle;
		
		private System.Nullable<char> _active;
		
		public Role()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleTitle", DbType="VarChar(200)")]
		public string roleTitle
		{
			get
			{
				return this._roleTitle;
			}
			set
			{
				if ((this._roleTitle != value))
				{
					this._roleTitle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="Char(1)")]
		public System.Nullable<char> active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this._active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _uname;
		
		private string _password;
		
		private string _name;
		
		private string _surname;
		
		private string _idNumber;
		
		private System.Nullable<int> _roleid;
		
		private string _gender;
		
		private string _active;
		
		private string _email;
		
		private string _cellNumber;
		
		private System.Nullable<System.DateTime> _dateCaptured;
		
		private System.Nullable<System.DateTime> _lastLogOn;
		
		private string _address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnunameChanging(string value);
    partial void OnunameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsurnameChanging(string value);
    partial void OnsurnameChanged();
    partial void OnidNumberChanging(string value);
    partial void OnidNumberChanged();
    partial void OnroleidChanging(System.Nullable<int> value);
    partial void OnroleidChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnactiveChanging(string value);
    partial void OnactiveChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncellNumberChanging(string value);
    partial void OncellNumberChanged();
    partial void OndateCapturedChanging(System.Nullable<System.DateTime> value);
    partial void OndateCapturedChanged();
    partial void OnlastLogOnChanging(System.Nullable<System.DateTime> value);
    partial void OnlastLogOnChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="VarChar(125)")]
		public string uname
		{
			get
			{
				return this._uname;
			}
			set
			{
				if ((this._uname != value))
				{
					this.OnunameChanging(value);
					this.SendPropertyChanging();
					this._uname = value;
					this.SendPropertyChanged("uname");
					this.OnunameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(125)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_surname", DbType="VarChar(50)")]
		public string surname
		{
			get
			{
				return this._surname;
			}
			set
			{
				if ((this._surname != value))
				{
					this.OnsurnameChanging(value);
					this.SendPropertyChanging();
					this._surname = value;
					this.SendPropertyChanged("surname");
					this.OnsurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNumber", DbType="VarChar(50)")]
		public string idNumber
		{
			get
			{
				return this._idNumber;
			}
			set
			{
				if ((this._idNumber != value))
				{
					this.OnidNumberChanging(value);
					this.SendPropertyChanging();
					this._idNumber = value;
					this.SendPropertyChanged("idNumber");
					this.OnidNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int")]
		public System.Nullable<int> roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_active", DbType="VarChar(20)")]
		public string active
		{
			get
			{
				return this._active;
			}
			set
			{
				if ((this._active != value))
				{
					this.OnactiveChanging(value);
					this.SendPropertyChanging();
					this._active = value;
					this.SendPropertyChanged("active");
					this.OnactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(125)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cellNumber", DbType="VarChar(20)")]
		public string cellNumber
		{
			get
			{
				return this._cellNumber;
			}
			set
			{
				if ((this._cellNumber != value))
				{
					this.OncellNumberChanging(value);
					this.SendPropertyChanging();
					this._cellNumber = value;
					this.SendPropertyChanged("cellNumber");
					this.OncellNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateCaptured", DbType="DateTime")]
		public System.Nullable<System.DateTime> dateCaptured
		{
			get
			{
				return this._dateCaptured;
			}
			set
			{
				if ((this._dateCaptured != value))
				{
					this.OndateCapturedChanging(value);
					this.SendPropertyChanging();
					this._dateCaptured = value;
					this.SendPropertyChanged("dateCaptured");
					this.OndateCapturedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastLogOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastLogOn
		{
			get
			{
				return this._lastLogOn;
			}
			set
			{
				if ((this._lastLogOn != value))
				{
					this.OnlastLogOnChanging(value);
					this.SendPropertyChanging();
					this._lastLogOn = value;
					this.SendPropertyChanged("lastLogOn");
					this.OnlastLogOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_DisplayAGYWInfo")]
	public partial class vw_DisplayAGYWInfo
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Surname;
		
		private string _IDorPassport;
		
		private System.Nullable<int> _Age;
		
		private string _Address;
		
		private string _FingerCode;
		
		private string _GPSCoordination;
		
		private string _region;
		
		private string _strPath;
		
		private string _UIdentifier;
		
		private string _dateofbirth;
		
		private string _contactNumber;
		
		public vw_DisplayAGYWInfo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(255)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDorPassport", DbType="VarChar(255)")]
		public string IDorPassport
		{
			get
			{
				return this._IDorPassport;
			}
			set
			{
				if ((this._IDorPassport != value))
				{
					this._IDorPassport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FingerCode", DbType="VarChar(255)")]
		public string FingerCode
		{
			get
			{
				return this._FingerCode;
			}
			set
			{
				if ((this._FingerCode != value))
				{
					this._FingerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSCoordination", DbType="VarChar(255)")]
		public string GPSCoordination
		{
			get
			{
				return this._GPSCoordination;
			}
			set
			{
				if ((this._GPSCoordination != value))
				{
					this._GPSCoordination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(50)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPath", DbType="VarChar(MAX)")]
		public string strPath
		{
			get
			{
				return this._strPath;
			}
			set
			{
				if ((this._strPath != value))
				{
					this._strPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIdentifier", DbType="VarChar(MAX)")]
		public string UIdentifier
		{
			get
			{
				return this._UIdentifier;
			}
			set
			{
				if ((this._UIdentifier != value))
				{
					this._UIdentifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofbirth", DbType="NVarChar(50)")]
		public string dateofbirth
		{
			get
			{
				return this._dateofbirth;
			}
			set
			{
				if ((this._dateofbirth != value))
				{
					this._dateofbirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="NVarChar(50)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this._contactNumber = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserRegistration")]
	public partial class UserRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _Surname;
		
		private string _IDorPassport;
		
		private System.Nullable<int> _Age;
		
		private string _Address;
		
		private string _FingerCode;
		
		private string _GPSCoordination;
		
		private string _region;
		
		private string _strPath;
		
		private string _UIdentifier;
		
		private string _dateofbirth;
		
		private string _contactNumber;
		
		private string _qualityAssured;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnIDorPassportChanging(string value);
    partial void OnIDorPassportChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnFingerCodeChanging(string value);
    partial void OnFingerCodeChanged();
    partial void OnGPSCoordinationChanging(string value);
    partial void OnGPSCoordinationChanged();
    partial void OnregionChanging(string value);
    partial void OnregionChanged();
    partial void OnstrPathChanging(string value);
    partial void OnstrPathChanged();
    partial void OnUIdentifierChanging(string value);
    partial void OnUIdentifierChanged();
    partial void OndateofbirthChanging(string value);
    partial void OndateofbirthChanged();
    partial void OncontactNumberChanging(string value);
    partial void OncontactNumberChanged();
    partial void OnqualityAssuredChanging(string value);
    partial void OnqualityAssuredChanged();
    #endregion
		
		public UserRegistration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(255)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDorPassport", DbType="VarChar(255)")]
		public string IDorPassport
		{
			get
			{
				return this._IDorPassport;
			}
			set
			{
				if ((this._IDorPassport != value))
				{
					this.OnIDorPassportChanging(value);
					this.SendPropertyChanging();
					this._IDorPassport = value;
					this.SendPropertyChanged("IDorPassport");
					this.OnIDorPassportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FingerCode", DbType="VarChar(255)")]
		public string FingerCode
		{
			get
			{
				return this._FingerCode;
			}
			set
			{
				if ((this._FingerCode != value))
				{
					this.OnFingerCodeChanging(value);
					this.SendPropertyChanging();
					this._FingerCode = value;
					this.SendPropertyChanged("FingerCode");
					this.OnFingerCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSCoordination", DbType="VarChar(255)")]
		public string GPSCoordination
		{
			get
			{
				return this._GPSCoordination;
			}
			set
			{
				if ((this._GPSCoordination != value))
				{
					this.OnGPSCoordinationChanging(value);
					this.SendPropertyChanging();
					this._GPSCoordination = value;
					this.SendPropertyChanged("GPSCoordination");
					this.OnGPSCoordinationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(50)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this.OnregionChanging(value);
					this.SendPropertyChanging();
					this._region = value;
					this.SendPropertyChanged("region");
					this.OnregionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPath", DbType="VarChar(MAX)")]
		public string strPath
		{
			get
			{
				return this._strPath;
			}
			set
			{
				if ((this._strPath != value))
				{
					this.OnstrPathChanging(value);
					this.SendPropertyChanging();
					this._strPath = value;
					this.SendPropertyChanged("strPath");
					this.OnstrPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIdentifier", DbType="VarChar(MAX)")]
		public string UIdentifier
		{
			get
			{
				return this._UIdentifier;
			}
			set
			{
				if ((this._UIdentifier != value))
				{
					this.OnUIdentifierChanging(value);
					this.SendPropertyChanging();
					this._UIdentifier = value;
					this.SendPropertyChanged("UIdentifier");
					this.OnUIdentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofbirth", DbType="NVarChar(50)")]
		public string dateofbirth
		{
			get
			{
				return this._dateofbirth;
			}
			set
			{
				if ((this._dateofbirth != value))
				{
					this.OndateofbirthChanging(value);
					this.SendPropertyChanging();
					this._dateofbirth = value;
					this.SendPropertyChanged("dateofbirth");
					this.OndateofbirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="NVarChar(50)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this.OncontactNumberChanging(value);
					this.SendPropertyChanging();
					this._contactNumber = value;
					this.SendPropertyChanged("contactNumber");
					this.OncontactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualityAssured", DbType="NVarChar(50)")]
		public string qualityAssured
		{
			get
			{
				return this._qualityAssured;
			}
			set
			{
				if ((this._qualityAssured != value))
				{
					this.OnqualityAssuredChanging(value);
					this.SendPropertyChanging();
					this._qualityAssured = value;
					this.SendPropertyChanged("qualityAssured");
					this.OnqualityAssuredChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QualityAssured")]
	public partial class QualityAssured
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Surname;
		
		private string _IDorPassport;
		
		private System.Nullable<int> _Age;
		
		private string _Address;
		
		private string _FingerCode;
		
		private string _GPSCoordination;
		
		private string _region;
		
		private string _strPath;
		
		private string _UIdentifier;
		
		private string _dateofbirth;
		
		private string _contactNumber;
		
		private string _qualityAssured1;
		
		public QualityAssured()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(255)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDorPassport", DbType="VarChar(255)")]
		public string IDorPassport
		{
			get
			{
				return this._IDorPassport;
			}
			set
			{
				if ((this._IDorPassport != value))
				{
					this._IDorPassport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FingerCode", DbType="VarChar(255)")]
		public string FingerCode
		{
			get
			{
				return this._FingerCode;
			}
			set
			{
				if ((this._FingerCode != value))
				{
					this._FingerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSCoordination", DbType="VarChar(255)")]
		public string GPSCoordination
		{
			get
			{
				return this._GPSCoordination;
			}
			set
			{
				if ((this._GPSCoordination != value))
				{
					this._GPSCoordination = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(50)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPath", DbType="VarChar(MAX)")]
		public string strPath
		{
			get
			{
				return this._strPath;
			}
			set
			{
				if ((this._strPath != value))
				{
					this._strPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIdentifier", DbType="VarChar(MAX)")]
		public string UIdentifier
		{
			get
			{
				return this._UIdentifier;
			}
			set
			{
				if ((this._UIdentifier != value))
				{
					this._UIdentifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofbirth", DbType="NVarChar(50)")]
		public string dateofbirth
		{
			get
			{
				return this._dateofbirth;
			}
			set
			{
				if ((this._dateofbirth != value))
				{
					this._dateofbirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="NVarChar(50)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this._contactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="qualityAssured", Storage="_qualityAssured1", DbType="NVarChar(50)")]
		public string qualityAssured1
		{
			get
			{
				return this._qualityAssured1;
			}
			set
			{
				if ((this._qualityAssured1 != value))
				{
					this._qualityAssured1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NotQualityAssured")]
	public partial class NotQualityAssured
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Surname;
		
		private string _IDorPassport;
		
		private System.Nullable<int> _Age;
		
		private string _Address;
		
		private string _FingerCode;
		
		private string _qualityAssured;
		
		private string _contactNumber;
		
		private string _dateofbirth;
		
		private string _UIdentifier;
		
		private string _strPath;
		
		private string _region;
		
		private string _GPSCoordination;
		
		public NotQualityAssured()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(255)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDorPassport", DbType="VarChar(255)")]
		public string IDorPassport
		{
			get
			{
				return this._IDorPassport;
			}
			set
			{
				if ((this._IDorPassport != value))
				{
					this._IDorPassport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this._Age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FingerCode", DbType="VarChar(255)")]
		public string FingerCode
		{
			get
			{
				return this._FingerCode;
			}
			set
			{
				if ((this._FingerCode != value))
				{
					this._FingerCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualityAssured", DbType="NVarChar(50)")]
		public string qualityAssured
		{
			get
			{
				return this._qualityAssured;
			}
			set
			{
				if ((this._qualityAssured != value))
				{
					this._qualityAssured = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNumber", DbType="NVarChar(50)")]
		public string contactNumber
		{
			get
			{
				return this._contactNumber;
			}
			set
			{
				if ((this._contactNumber != value))
				{
					this._contactNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateofbirth", DbType="NVarChar(50)")]
		public string dateofbirth
		{
			get
			{
				return this._dateofbirth;
			}
			set
			{
				if ((this._dateofbirth != value))
				{
					this._dateofbirth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIdentifier", DbType="VarChar(MAX)")]
		public string UIdentifier
		{
			get
			{
				return this._UIdentifier;
			}
			set
			{
				if ((this._UIdentifier != value))
				{
					this._UIdentifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strPath", DbType="VarChar(MAX)")]
		public string strPath
		{
			get
			{
				return this._strPath;
			}
			set
			{
				if ((this._strPath != value))
				{
					this._strPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(50)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSCoordination", DbType="VarChar(255)")]
		public string GPSCoordination
		{
			get
			{
				return this._GPSCoordination;
			}
			set
			{
				if ((this._GPSCoordination != value))
				{
					this._GPSCoordination = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
